plugins:
  - jekyll-redirect-from

# GitHub Pages settings
permalink: pretty

# Enable directory indexes
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Include auth directory
include:
  - auth
  - auth/callback

# Exclude unnecessary files
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
